export const views = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_FAILURE: 'VERIFY_FAILURE',
  PROFILE: 'PROFILE',
  ADD_CARD: 'ADD_CARD',
  VIEW_PROFILE: 'VIEW_PROFILE',
  VIEW_PRODUCTS: 'VIEW_PRODUCTS',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  EDIT_PROFILE: 'EDIT_PROFILE',
  VIEW_CARD: 'VIEW_CARD',
  ACTIVATE_ACCOUNT: 'ACTIVATE_ACCOUNT'
}
