export const AppTypes = {
  SUBMITTING: '@app/SUBMITTING',
  REGISTER_REQUEST: '@app/REGISTER_REQUEST',
  REGISTER_SUCCESS: '@app/REGISTER_SUCCESS',
  REGISTER_FAILURE: '@app/REGISTER_FAILURE',

  ACTIVATE_REQUEST: '@app/ACTIVATE_REQUEST',
  ACTIVATE_SUCCESS: '@app/ACTIVATE_SUCCESS',
  ACTIVATE_FAILURE: '@app/ACTIVATE_FAILURE',

  LOGIN_REQUEST: '@app/LOGIN_REQUEST',
  LOGIN_SUCCESS: '@app/LOGIN_SUCCESS',
  LOGIN_FAILURE: '@app/LOGIN_FAILURE',

  DESTROY_STATES: '@app/DESTROY_STATES',
  SET_CURRENT_USER: '@app/SET_CURRENT_USER',
  CLEAR_STATES: '@app/CLEAR_STATES',

  SET_VIEW: '@pp/SET_VIEW',
  LOGOUT: '@pp/LOGOUT',

  GET_USER_REQUEST: '@app/GET_USER_REQUEST',
  GET_USER_SUCCESS: '@app/GET_USER_SUCCESS',
  GET_USER_FAILURE: '@app/GET_USER_FAILURE',
  GET_PRODUCTS_REQUEST: '@app/GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: '@app/GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: '@app/GET_PRODUCTS_FAILURE',

  GET_USER_CARDS_REQUEST: '@app/GET_USER_CARDS_REQUEST',
  GET_USER_CARDS_SUCCESS: '@app/GET_USER_CARDS_SUCCESS',
  GET_USER_CARDS_FAILURE: '@app/GET_USER_CARDS_FAILURE',

  ADD_CARD_REQUEST: '@app/ADD_CARD_REQUEST',
  ADD_CARD_SUCCESS: '@app/ADD_CARD_SUCCESS',
  ADD_CARD_FAILURE: '@app/ADD_CARD_FAILURE',

  SET_USER_CARD: '@app/SET_USER_CARD',
  SET_USER_PRODUCT: '@app/SET_USER_PRODUCT',

  FORGOTTEN_PASSWORD_REQUEST: '@app/FORGOTTEN_PASSWORD_REQUEST',
  FORGOTTEN_PASSWORD_SUCCESS: '@app/FORGOTTEN_PASSWORD_SUCCESS',
  FORGOTTEN_PASSWORD_FAILURE: '@app/FORGOTTEN_PASSWORD_FAILURE',

  RESET_PASSWORD_REQUEST: '@app/RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: '@app/RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: '@app/RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD_REQUEST: '@app/CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: '@app/CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: '@app/CHANGE_PASSWORD_FAILURE',

  EDIT_PROFILE_REQUEST: '@app/EDIT_PROFILE_REQUEST',
  EDIT_PROFILE_SUCCESS: '@app/EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: '@app/EDIT_PROFILE_FAILURE'
}
